#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'no argument'
    exit 0
fi

cd `dirname $0`
cp .template.cpp source/$1.cpp
#echo "add_executable($1 $1.cpp)" >> source/CMakeLists.txt
echo -e "add_executable($1 $1.cpp)\nadd_custom_command(\n    TARGET $1\n    PRE_BUILD\n    COMMAND \${CMAKE_CURRENT_SOURCE_DIR}/../merge_std2.sh ${1}
\n    WORKING_DIRECTORY \${CMAKE_CURRENT_SOURCE_DIR}\n    COMMENT \"Merging headers for $1\"\n)" >> source/CMakeLists.txt
